
name: Deploy Rust Docs

# Will trigger for each push on main
on:
  push:
    branches:
      - main

# allow to read the repo content
# allow to edit on Github Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
    # This clone the repo in the remote VM for next steps
    - name: Checkout code 
      uses: actions/checkout@v4

    # Installs rust on the remote VM 
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    # runs the command cargo doc : no deps for lightweight site
    - name: Build documentation
      run: cargo doc --no-deps --all-features

    # store the target/doc so the next job can use it
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: target/doc

  deploy:
    needs: build # indicate that the last job "build" must be done to start
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # allow to have the link for the github pages at the end of the deployment
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # this is the artifact we generated at end of build job

